const proovedores = {
  title: "Proovedores",
  inputs: [
    {
      input: "Input",
      type: "text",
      key: "name",
      name: "name",
      placeHolder: "Escriba su nombre",
      columnLocation: "1 / 6",
      rowLocation: "1",
      isRequired: true,
    },
    {
      input: "Input",
      type: "text",
      key: "address",
      name: "address",
      placeHolder: "Escriba su dirección",
      columnLocation: "6 / 12",
      rowLocation: "1",
      isRequired: true,
    },
    {
      input: "Input",
      type: "checkbox",
      key: "active",
      placeHolder: "Opción 1",
      position: "right",
      columnLocation: "6/12",
      rowLocation: "2",
      isRequired: false,
    },
    {
      input: "List",
      type: "",
      name: "risk",
      key: "risk",
      options: [
        { value: "bajo", label: "bajo" },
        { value: "moderado", label: "moderado" },
        { value: "medio", label: "medio" },
        { value: "alto", label: "alto" },
        { value: "muy alto", label: "muy alto" },
      ],
      placeHolder: "Escriba su dirección",
      columnLocation: "1/6",
      rowLocation: "3",
      isRequired: false,
    },
  ],
};

const clientes = {
  title: "Clientes",
  inputs: [
    {
      input: "Input",
      type: "text",
      name: "ciudad",
      key: "city",
      placeHolder: "Escriba su nombre",
      columnLocation: "1 / 12",
      rowLocation: "1",
      isRequired: true,
    },
    {
      input: "List",
      type: "",
      name: "antiguedad",
      key: "time",
      options: [
        { value: "menos de 1 año", label: "menos de 1 año" },
        { value: "de 1 a 3 años", label: "de 1 a 3 años" },
        { value: "de 3 a 5 años", label: "de 3 a 5 años" },
        { value: "mas de 5 años", label: "mas de 5 años" },
      ],
      columnLocation: "1 / 6",
      rowLocation: "2",
      isRequired: true,
    },
    {
      input: "Input",
      type: "text",
      name: "dirección",
      key: "address",
      placeHolder: "Escriba su dirección",
      columnLocation: "6/12",
      rowLocation: "2",
      isRequired: false,
    },
    {
      input: "List",
      type: "",
      name: "frecuencia",
      key: "frequency",
      options: [
        { label: "bajo", value: "bajo" },
        { value: "moderado", label: "moderado" },
        { value: "medio", label: "medio" },
        { value: "alto", label: "alto" },
        { value: "muy alto", label: "muy alto" },
      ],
      columnLocation: "6/12",
      rowLocation: "3",
      isRequired: false,
    },
  ],
};

export const Tables = {
  proovedores: proovedores,
  clientes: clientes,
};
