const userConfirmationCopy = [
  {
    title: 'Confirma tu usuario',
    subtitle1: '¡Ingresa tus datos para empezar!',
    resendCode: 'Reenviar código',
    email: 'Correo electronico',
    password: 'Contraseña',
    validationCode: 'Código de confirmación',
    terms: 'Acepto los Términos de Servicio y Política de Privacidad',
    button: 'Confirmar',
    label1: '1 Mayúscula',
    label2: '1 Minúscula',
    label3: '1 Número',
    label4: '8 Carácteres',
    terms1: 'Acepto los ',
    anchor1: 'Termínos y Condiciones de Uso',
    terms2: 'Acepto la ',
    anchor2: 'Política de Tratamiento de Datos personales',
  },
  {
    title: 'Confirm your username',
    subtitle1: 'Enter your details to get started!',
    resendCode: 'Resend code',
    email: 'email',
    validationCode: 'Confirmation code',
    password: 'Password',
    terms: 'Acepto los Términos de Servicio y Política de Privacidad',
    button: 'Confirmar',
    label1: '1 uppercase',
    label2: '1 lowercase',
    label3: '1 Number',
    label4: '8 characters',
    terms1: 'I accept the ',
    anchor1: 'terms and conditions of use',
    terms2: 'I accept the ',
    anchor2: 'data treatment policy',
  },
];

export default userConfirmationCopy;
